name: clotheline_core
description: Shared models, services, and logic for Clotheline Customer and Admin apps.
version: 1.5.0+40
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  http: ^1.1.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  flutter_local_notifications: ^20.1.0
  latlong2: ^0.9.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.10
  permission_handler: ^11.3.1

  # Internal
  liquid_glass_ui:
    path: ../liquid_glass_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
