name: Android Release Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android App Bundle
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx6g"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Decode Keystore
        working-directory: ./mobile_app
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create Key Properties
        working-directory: ./mobile_app
        run: |
          echo "${{ secrets.KEY_PROPERTIES_CONTENTS }}" > android/key.properties

      - name: Create Google Services JSON
        working-directory: ./mobile_app
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      - name: Flutter Doctor
        working-directory: ./mobile_app
        run: flutter doctor -v

      - name: Clean Gradle Cache
        working-directory: ./mobile_app
        run: |
          flutter clean
          rm -rf ~/.gradle
          rm -rf ~/.android
          rm -rf android/.gradle
          flutter pub get

      - name: Get Dependencies
        working-directory: ./mobile_app
        run: flutter pub get

      - name: Build App Bundle
        working-directory: ./mobile_app
        run: flutter build appbundle --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: mobile_app/build/app/outputs/bundle/release/app-release.aab
          retention-days: 7
